name: docs
on:
  push:
    banches:
      - "main"
    paths:
      - "DOCS.org"
      - ".github/workflows/docs.yml"
jobs:
  build-docs:
    runs-on: ubuntu-latest
    name: pandoc to vimdoc
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: panvimdoc
        uses: kdheepak/panvimdoc@v4.0.1
        with:
          vimdoc: org-roam
          pandoc: DOCS.org
          toc: true
          treesitter: true
          version: "NVIM v0.9.2"
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Auto generate docs"
